version: '3.9'

services:
  backend:
    image: ludos-backend
    build: .
    command: "npm run start:dev"
    volumes:
      - ./src:/app/src
    ports:
      - 8080:8080
    links:
      - postgres
    environment:
      - DB_SSL__REJECT_UNAUTHORIZED=false
  postgres:
    image: postgres:14-alpine
    ports:
      - 35432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=ludos
volumes:
  postgres: