version: "3.9"

services:
  frontend:
    image: ludos-frontend
    build: 
      target: dev
      context: .
    command: "npm start"
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000
