name: Unit Tests

on:
  pull_request:
    branches:
      - main
      - development
    paths:
      - 'ludos/backend/**'

jobs:
  unit-tests:
    name: Unit Tests

    strategy:
      matrix:
        runs-on: [ubuntu-latest]

    runs-on: ${{ matrix.runs-on }}

    defaults:
      run:
        working-directory: ./ludos/backend

    steps:
      - name: Checkout the files
        uses: actions/checkout@v3

      - name: Set Node.js 19.x
        uses: actions/setup-node@v3
        with:
          node-version: 19.x

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{matrix.node-version}}

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Run unit tests
        run: npm test

      - name: Lint
        run: npm run lint